version: '3.8'

services:
  # IPFS service
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: martzk-ipfs
    ports:
      - "4001:4001"     # P2P swarm port
      - "5001:5001"     # API port
      - "8080:8080"     # Gateway port
    volumes:
      - ipfs_data:/data/ipfs
      - ipfs_staging:/export
    environment:
      - IPFS_PROFILE=server
    networks:
      - martzk-network

  # MARTZK Benchmark service (using main Dockerfile)
  martzk-benchmark:
    build:
      context: .
      dockerfile: dockerfile  # Use main Dockerfile
    container_name: martzk-benchmark
    depends_on:
      - ipfs
    volumes:
      - ./src:/test/src
      - ./output_files:/test/output_files
      - ./databases:/test/databases
      - ./logs:/test/logs
      - ./circuits:/test/circuits
      - ./json_files:/test/json_files
      - ./benchmark_results:/test/benchmark_results
      - ./benchmark_charts:/test/benchmark_charts
    environment:
      - PYTHONPATH=/test/src:/test
      - IPFS_HOST=ipfs
      - IPFS_PORT=5001
      - PROCESS_INSTANCE_ID=14346233703771857702
    networks:
      - martzk-network
    working_dir: /test
    command: ["python3", "src/benchmark_martzk.py", "--iterations", "100"]

  # Quick benchmark service (for testing)
  martzk-benchmark-quick:
    build:
      context: .
      dockerfile: dockerfile  # Use main Dockerfile
    container_name: martzk-benchmark-quick
    depends_on:
      - ipfs
    volumes:
      - ./src:/test/src
      - ./output_files:/test/output_files
      - ./databases:/test/databases
      - ./logs:/test/logs
      - ./circuits:/test/circuits
      - ./json_files:/test/json_files
      - ./benchmark_results:/test/benchmark_results
      - ./benchmark_charts:/test/benchmark_charts
    environment:
      - PYTHONPATH=/test/src:/test
      - IPFS_HOST=ipfs
      - IPFS_PORT=5001
      - PROCESS_INSTANCE_ID=14346233703771857702
    networks:
      - martzk-network
    working_dir: /test
    command: ["python3", "src/benchmark_martzk.py", "--quick"]
    profiles:
      - quick

  # Results viewer service (for viewing charts)
  results-viewer:
    build:
      context: .
      dockerfile: dockerfile  # Use main Dockerfile
    container_name: martzk-results-viewer
    volumes:
      - ./benchmark_results:/test/benchmark_results
      - ./benchmark_charts:/test/benchmark_charts
      - ./src:/test/src
    environment:
      - PYTHONPATH=/test/src:/test
    networks:
      - martzk-network
    working_dir: /test
    command: ["python3", "src/visualize_results.py"]
    profiles:
      - viewer

volumes:
  ipfs_data:
  ipfs_staging:

networks:
  martzk-network:
    driver: bridge 